name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  badges: ^3.1.2
  cloud_firestore: ^4.15.8
  curved_labeled_navigation_bar: ^2.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.7.1
  flutter:
    sdk: flutter
  flutter_social_button: ^1.1.4+1
  image_picker: ^1.0.7
  lottie: ^3.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
