// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:952908336305:web:9d61e8f9d46ecc9c5fe690',
    messagingSenderId: '952908336305',
    projectId: 'chatapp-61cfc',
    authDomain: 'xxxxxxxxx.firebaseapp.com',
    storageBucket: 'xxxxxxxxxxxxx.appspot.com',
    measurementId: 'G-9BK1KZ57Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:952908336305:android:99396e312cde98985fe690',
    messagingSenderId: '952908336305',
    projectId: 'xxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxxxxx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:952908336305:ios:c8c7605e7c9330c45fe690',
    messagingSenderId: '952908336305',
    projectId: 'chatapp-61cfc',
    storageBucket: 'xxxxxxxxxxxxxxxxxxx.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:952908336305:ios:06123144986729c75fe690',
    messagingSenderId: '952908336305',
    projectId: 'xxxxxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxx.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
